package test

import (
	"RyzeSCA/grpc/server/ryzesca"
	"context"
	"fmt"
	"google.golang.org/grpc"
	"testing"
)

func TestThemisServer_RunThemisCycloneDX(t *testing.T) {

	//	sbom := `{
	//  "$schema":"http://cyclonedx.org/schema/bom-1.4.schema.json",
	//  "bomFormat":"CycloneDX",
	//  "components":[
	//    {
	//      "bom-ref":"pkg:maven/org.springframework.boot/spring-boot-starter-json@2.2.2.RELEASE?type=jar",
	//      "name":"spring-boot-starter-json",
	//      "purl":"pkg:maven/org.springframework.boot/spring-boot-starter-json@2.2.2.RELEASE?type=jar",
	//      "type":"library",
	//      "version":"2.2.2.RELEASE"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/javax.xml.bind/jaxb-api@2.3.1?type=jar",
	//      "name":"jaxb-api",
	//      "purl":"pkg:maven/javax.xml.bind/jaxb-api@2.3.1?type=jar",
	//      "type":"library",
	//      "version":"2.3.1"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/io.undertow/undertow-servlet@2.0.28.Final?type=jar",
	//      "name":"undertow-servlet",
	//      "purl":"pkg:maven/io.undertow/undertow-servlet@2.0.28.Final?type=jar",
	//      "type":"library",
	//      "version":"2.0.28.Final"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.springframework.boot/spring-boot-autoconfigure@2.2.2.RELEASE?type=jar",
	//      "name":"spring-boot-autoconfigure",
	//      "purl":"pkg:maven/org.springframework.boot/spring-boot-autoconfigure@2.2.2.RELEASE?type=jar",
	//      "type":"library",
	//      "version":"2.2.2.RELEASE"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.glassfish.jaxb/jaxb-runtime@2.3.2?type=jar",
	//      "name":"jaxb-runtime",
	//      "purl":"pkg:maven/org.glassfish.jaxb/jaxb-runtime@2.3.2?type=jar",
	//      "type":"library",
	//      "version":"2.3.2"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/javax.activation/activation@1.1.1?type=jar",
	//      "name":"activation",
	//      "purl":"pkg:maven/javax.activation/activation@1.1.1?type=jar",
	//      "type":"library",
	//      "version":"1.1.1"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.unbescape/unbescape@1.1.6.RELEASE?type=jar",
	//      "name":"unbescape",
	//      "purl":"pkg:maven/org.unbescape/unbescape@1.1.6.RELEASE?type=jar",
	//      "type":"library",
	//      "version":"1.1.6.RELEASE"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.springframework.boot/spring-boot-starter-data-jpa@2.2.2.RELEASE?type=jar",
	//      "name":"spring-boot-starter-data-jpa",
	//      "purl":"pkg:maven/org.springframework.boot/spring-boot-starter-data-jpa@2.2.2.RELEASE?type=jar",
	//      "type":"library",
	//      "version":"2.2.2.RELEASE"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.hsqldb.hsqldb/hsqldb@2.5.0?type=jar",
	//      "name":"hsqldb",
	//      "purl":"pkg:maven/org.hsqldb.hsqldb/hsqldb@2.5.0?type=jar",
	//      "type":"library",
	//      "version":"2.5.0"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/jakarta.persistence/jakarta.persistence-api@2.2.3?type=jar",
	//      "name":"jakarta.persistence-api",
	//      "purl":"pkg:maven/jakarta.persistence/jakarta.persistence-api@2.2.3?type=jar",
	//      "type":"library",
	//      "version":"2.2.3"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.owasp.webgoat.lesson/csrf@8.1.0?type=jar",
	//      "name":"csrf",
	//      "purl":"pkg:maven/org.owasp.webgoat.lesson/csrf@8.1.0?type=jar",
	//      "type":"library",
	//      "version":"8.1.0"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.springframework.boot/spring-boot-starter-jdbc@2.2.2.RELEASE?type=jar",
	//      "name":"spring-boot-starter-jdbc",
	//      "purl":"pkg:maven/org.springframework.boot/spring-boot-starter-jdbc@2.2.2.RELEASE?type=jar",
	//      "type":"library",
	//      "version":"2.2.2.RELEASE"
	//    },
	//    {
	//      "bom-ref":"pkg:maven//asciidoctorj@1.5.8.1?type=jar",
	//      "name":"asciidoctorj",
	//      "purl":"pkg:maven//asciidoctorj@1.5.8.1?type=jar",
	//      "type":"library",
	//      "version":"1.5.8.1"
	//    },
	//    {
	//      "bom-ref":"pkg:maven//cglib-nodep@2.2?type=jar",
	//      "name":"cglib-nodep",
	//      "purl":"pkg:maven//cglib-nodep@2.2?type=jar",
	//      "type":"library",
	//      "version":"2.2"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.springframework.boot/spring-boot-starter-validation@2.2.2.RELEASE?type=jar",
	//      "name":"spring-boot-starter-validation",
	//      "purl":"pkg:maven/org.springframework.boot/spring-boot-starter-validation@2.2.2.RELEASE?type=jar",
	//      "type":"library",
	//      "version":"2.2.2.RELEASE"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.owasp.webgoat.lesson/insecure-login@8.1.0?type=jar",
	//      "name":"insecure-login",
	//      "purl":"pkg:maven/org.owasp.webgoat.lesson/insecure-login@8.1.0?type=jar",
	//      "type":"library",
	//      "version":"8.1.0"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.owasp.webgoat.lesson/xxe@8.1.0?type=jar",
	//      "name":"xxe",
	//      "purl":"pkg:maven/org.owasp.webgoat.lesson/xxe@8.1.0?type=jar",
	//      "type":"library",
	//      "version":"8.1.0"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.springframework/spring-aspects@5.2.2.RELEASE?type=jar",
	//      "name":"spring-aspects",
	//      "purl":"pkg:maven/org.springframework/spring-aspects@5.2.2.RELEASE?type=jar",
	//      "type":"library",
	//      "version":"5.2.2.RELEASE"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.springframework.boot/spring-boot@2.2.2.RELEASE?type=jar",
	//      "name":"spring-boot",
	//      "purl":"pkg:maven/org.springframework.boot/spring-boot@2.2.2.RELEASE?type=jar",
	//      "type":"library",
	//      "version":"2.2.2.RELEASE"
	//    },
	//    {
	//      "bom-ref":"pkg:maven//zxcvbn@1.2.5?type=jar",
	//      "name":"zxcvbn",
	//      "purl":"pkg:maven//zxcvbn@1.2.5?type=jar",
	//      "type":"library",
	//      "version":"1.2.5"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.springframework.boot/spring-boot-actuator-autoconfigure@2.2.2.RELEASE?type=jar",
	//      "name":"spring-boot-actuator-autoconfigure",
	//      "purl":"pkg:maven/org.springframework.boot/spring-boot-actuator-autoconfigure@2.2.2.RELEASE?type=jar",
	//      "type":"library",
	//      "version":"2.2.2.RELEASE"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/com.beust/jcommander@1.35?type=jar",
	//      "name":"jcommander",
	//      "purl":"pkg:maven/com.beust/jcommander@1.35?type=jar",
	//      "type":"library",
	//      "version":"1.35"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.springframework/spring-orm@5.2.2.RELEASE?type=jar",
	//      "name":"spring-orm",
	//      "purl":"pkg:maven/org.springframework/spring-orm@5.2.2.RELEASE?type=jar",
	//      "type":"library",
	//      "version":"5.2.2.RELEASE"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.owasp.webgoat.lesson/bypass-restrictions@8.1.0?type=jar",
	//      "name":"bypass-restrictions",
	//      "purl":"pkg:maven/org.owasp.webgoat.lesson/bypass-restrictions@8.1.0?type=jar",
	//      "type":"library",
	//      "version":"8.1.0"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.owasp.webgoat.lesson/vulnerable-components@8.1.0?type=jar",
	//      "name":"vulnerable-components",
	//      "purl":"pkg:maven/org.owasp.webgoat.lesson/vulnerable-components@8.1.0?type=jar",
	//      "type":"library",
	//      "version":"8.1.0"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.springframework.boot/spring-boot-starter-security@2.2.2.RELEASE?type=jar",
	//      "name":"spring-boot-starter-security",
	//      "purl":"pkg:maven/org.springframework.boot/spring-boot-starter-security@2.2.2.RELEASE?type=jar",
	//      "type":"library",
	//      "version":"2.2.2.RELEASE"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.antlr/antlr@2.7.7?type=jar",
	//      "name":"antlr",
	//      "purl":"pkg:maven/org.antlr/antlr@2.7.7?type=jar",
	//      "type":"library",
	//      "version":"2.7.7"
	//    },
	//    {
	//      "bom-ref":"pkg:maven//byte-buddy@1.10.4?type=jar",
	//      "name":"byte-buddy",
	//      "purl":"pkg:maven//byte-buddy@1.10.4?type=jar",
	//      "type":"library",
	//      "version":"1.10.4"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.springframework/spring-aop@5.2.2.RELEASE?type=jar",
	//      "name":"spring-aop",
	//      "purl":"pkg:maven/org.springframework/spring-aop@5.2.2.RELEASE?type=jar",
	//      "type":"library",
	//      "version":"5.2.2.RELEASE"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.jvnet.staxex/stax-ex@1.8.1?type=jar",
	//      "name":"stax-ex",
	//      "purl":"pkg:maven/org.jvnet.staxex/stax-ex@1.8.1?type=jar",
	//      "type":"library",
	//      "version":"1.8.1"
	//    },
	//    {
	//      "bom-ref":"pkg:maven//jakarta.annotation-api@1.3.5?type=jar",
	//      "name":"jakarta.annotation-api",
	//      "purl":"pkg:maven//jakarta.annotation-api@1.3.5?type=jar",
	//      "type":"library",
	//      "version":"1.3.5"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.apache.logging.log4j/log4j-to-slf4j@2.12.1?type=jar",
	//      "name":"log4j-to-slf4j",
	//      "purl":"pkg:maven/org.apache.logging.log4j/log4j-to-slf4j@2.12.1?type=jar",
	//      "type":"library",
	//      "version":"2.12.1"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/com.ongres.stringprep/stringprep@1.1?type=jar",
	//      "name":"stringprep",
	//      "purl":"pkg:maven/com.ongres.stringprep/stringprep@1.1?type=jar",
	//      "type":"library",
	//      "version":"1.1"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.owasp.webgoat.lesson/secure-passwords@8.1.0?type=jar",
	//      "name":"secure-passwords",
	//      "purl":"pkg:maven/org.owasp.webgoat.lesson/secure-passwords@8.1.0?type=jar",
	//      "type":"library",
	//      "version":"8.1.0"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.thymeleaf/thymeleaf-spring5@3.0.11.RELEASE?type=jar",
	//      "name":"thymeleaf-spring5",
	//      "purl":"pkg:maven/org.thymeleaf/thymeleaf-spring5@3.0.11.RELEASE?type=jar",
	//      "type":"library",
	//      "version":"3.0.11.RELEASE"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.springframework/spring-web@5.2.2.RELEASE?type=jar",
	//      "name":"spring-web",
	//      "purl":"pkg:maven/org.springframework/spring-web@5.2.2.RELEASE?type=jar",
	//      "type":"library",
	//      "version":"5.2.2.RELEASE"
	//    },
	//    {
	//      "bom-ref":"pkg:maven//aspectjweaver@1.9.5?type=jar",
	//      "name":"aspectjweaver",
	//      "purl":"pkg:maven//aspectjweaver@1.9.5?type=jar",
	//      "type":"library",
	//      "version":"1.9.5"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.owasp.webgoat.lesson/webgoat-introduction@8.1.0?type=jar",
	//      "name":"webgoat-introduction",
	//      "purl":"pkg:maven/org.owasp.webgoat.lesson/webgoat-introduction@8.1.0?type=jar",
	//      "type":"library",
	//      "version":"8.1.0"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.owasp.webgoat.lesson/password-reset@8.1.0?type=jar",
	//      "name":"password-reset",
	//      "purl":"pkg:maven/org.owasp.webgoat.lesson/password-reset@8.1.0?type=jar",
	//      "type":"library",
	//      "version":"8.1.0"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.flywaydb/flyway-core@6.0.8?type=jar",
	//      "name":"flyway-core",
	//      "purl":"pkg:maven/org.flywaydb/flyway-core@6.0.8?type=jar",
	//      "type":"library",
	//      "version":"6.0.8"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.springframework.data/spring-data-commons@2.2.3.RELEASE?type=jar",
	//      "name":"spring-data-commons",
	//      "purl":"pkg:maven/org.springframework.data/spring-data-commons@2.2.3.RELEASE?type=jar",
	//      "type":"library",
	//      "version":"2.2.3.RELEASE"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/com.fasterxml.jackson.datatype/jackson-datatype-jsr310@2.10.1?type=jar",
	//      "name":"jackson-datatype-jsr310",
	//      "purl":"pkg:maven/com.fasterxml.jackson.datatype/jackson-datatype-jsr310@2.10.1?type=jar",
	//      "type":"library",
	//      "version":"2.10.1"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.springframework.boot/spring-boot-starter@2.2.2.RELEASE?type=jar",
	//      "name":"spring-boot-starter",
	//      "purl":"pkg:maven/org.springframework.boot/spring-boot-starter@2.2.2.RELEASE?type=jar",
	//      "type":"library",
	//      "version":"2.2.2.RELEASE"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.attoparser/attoparser@2.0.5.RELEASE?type=jar",
	//      "name":"attoparser",
	//      "purl":"pkg:maven/org.attoparser/attoparser@2.0.5.RELEASE?type=jar",
	//      "type":"library",
	//      "version":"2.0.5.RELEASE"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.slf4j/jul-to-slf4j@1.7.29?type=jar",
	//      "name":"jul-to-slf4j",
	//      "purl":"pkg:maven/org.slf4j/jul-to-slf4j@1.7.29?type=jar",
	//      "type":"library",
	//      "version":"1.7.29"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.springframework.security/spring-security-core@5.2.1.RELEASE?type=jar",
	//      "name":"spring-security-core",
	//      "purl":"pkg:maven/org.springframework.security/spring-security-core@5.2.1.RELEASE?type=jar",
	//      "type":"library",
	//      "version":"5.2.1.RELEASE"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/commons-lang/commons-lang@2.6?type=jar",
	//      "name":"commons-lang",
	//      "purl":"pkg:maven/commons-lang/commons-lang@2.6?type=jar",
	//      "type":"library",
	//      "version":"2.6"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.springframework/spring-core@5.2.2.RELEASE?type=jar",
	//      "name":"spring-core",
	//      "purl":"pkg:maven/org.springframework/spring-core@5.2.2.RELEASE?type=jar",
	//      "type":"library",
	//      "version":"5.2.2.RELEASE"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.springframework/spring-beans@5.2.2.RELEASE?type=jar",
	//      "name":"spring-beans",
	//      "purl":"pkg:maven/org.springframework/spring-beans@5.2.2.RELEASE?type=jar",
	//      "type":"library",
	//      "version":"5.2.2.RELEASE"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.thymeleaf/thymeleaf@3.0.11.RELEASE?type=jar",
	//      "name":"thymeleaf",
	//      "purl":"pkg:maven/org.thymeleaf/thymeleaf@3.0.11.RELEASE?type=jar",
	//      "type":"library",
	//      "version":"3.0.11.RELEASE"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/com.thoughtworks.xstream/xstream@1.4.5?type=jar",
	//      "name":"xstream",
	//      "purl":"pkg:maven/com.thoughtworks.xstream/xstream@1.4.5?type=jar",
	//      "type":"library",
	//      "version":"1.4.5"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.owasp.webgoat.lesson/cross-site-scripting@8.1.0?type=jar",
	//      "name":"cross-site-scripting",
	//      "purl":"pkg:maven/org.owasp.webgoat.lesson/cross-site-scripting@8.1.0?type=jar",
	//      "type":"library",
	//      "version":"8.1.0"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/io.undertow/undertow-websockets-jsr@2.0.28.Final?type=jar",
	//      "name":"undertow-websockets-jsr",
	//      "purl":"pkg:maven/io.undertow/undertow-websockets-jsr@2.0.28.Final?type=jar",
	//      "type":"library",
	//      "version":"2.0.28.Final"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.apache.logging.log4j/log4j-api@2.12.1?type=jar",
	//      "name":"log4j-api",
	//      "purl":"pkg:maven/org.apache.logging.log4j/log4j-api@2.12.1?type=jar",
	//      "type":"library",
	//      "version":"2.12.1"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.owasp.webgoat.lesson/http-basics@8.1.0?type=jar",
	//      "name":"http-basics",
	//      "purl":"pkg:maven/org.owasp.webgoat.lesson/http-basics@8.1.0?type=jar",
	//      "type":"library",
	//      "version":"8.1.0"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.glassfish.jaxb/txw2@2.3.2?type=jar",
	//      "name":"txw2",
	//      "purl":"pkg:maven/org.glassfish.jaxb/txw2@2.3.2?type=jar",
	//      "type":"library",
	//      "version":"2.3.2"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.jboss.spec.javax.websocket/jboss-websocket-api_1.1_spec@1.1.4.Final?type=jar",
	//      "name":"jboss-websocket-api_1.1_spec",
	//      "purl":"pkg:maven/org.jboss.spec.javax.websocket/jboss-websocket-api_1.1_spec@1.1.4.Final?type=jar",
	//      "type":"library",
	//      "version":"1.1.4.Final"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.thymeleaf.extras/thymeleaf-extras-springsecurity5@3.0.4.RELEASE?type=jar",
	//      "name":"thymeleaf-extras-springsecurity5",
	//      "purl":"pkg:maven/org.thymeleaf.extras/thymeleaf-extras-springsecurity5@3.0.4.RELEASE?type=jar",
	//      "type":"library",
	//      "version":"3.0.4.RELEASE"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.owasp.webgoat.lesson/auth-bypass@8.1.0?type=jar",
	//      "name":"auth-bypass",
	//      "purl":"pkg:maven/org.owasp.webgoat.lesson/auth-bypass@8.1.0?type=jar",
	//      "type":"library",
	//      "version":"8.1.0"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.owasp.webgoat.lesson/idor@8.1.0?type=jar",
	//      "name":"idor",
	//      "purl":"pkg:maven/org.owasp.webgoat.lesson/idor@8.1.0?type=jar",
	//      "type":"library",
	//      "version":"8.1.0"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.hibernate.orm.core/hibernate-core@5.4.9.Final?type=jar",
	//      "name":"hibernate-core",
	//      "purl":"pkg:maven/org.hibernate.orm.core/hibernate-core@5.4.9.Final?type=jar",
	//      "type":"library",
	//      "version":"5.4.9.Final"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.jboss.xnio/xnio-api@3.3.8.Final?type=jar",
	//      "name":"xnio-api",
	//      "purl":"pkg:maven/org.jboss.xnio/xnio-api@3.3.8.Final?type=jar",
	//      "type":"library",
	//      "version":"3.3.8.Final"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/javax.activation/javax.activation-api@1.2.0?type=jar",
	//      "name":"javax.activation-api",
	//      "purl":"pkg:maven/javax.activation/javax.activation-api@1.2.0?type=jar",
	//      "type":"library",
	//      "version":"1.2.0"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.owasp.webgoat/webgoat-container@8.1.0?type=jar",
	//      "name":"webgoat-container",
	//      "purl":"pkg:maven/org.owasp.webgoat/webgoat-container@8.1.0?type=jar",
	//      "type":"library",
	//      "version":"8.1.0"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/jakarta.servlet/jakarta.servlet-api@4.0.3?type=jar",
	//      "name":"jakarta.servlet-api",
	//      "purl":"pkg:maven/jakarta.servlet/jakarta.servlet-api@4.0.3?type=jar",
	//      "type":"library",
	//      "version":"4.0.3"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.springframework/spring-jdbc@5.2.2.RELEASE?type=jar",
	//      "name":"spring-jdbc",
	//      "purl":"pkg:maven/org.springframework/spring-jdbc@5.2.2.RELEASE?type=jar",
	//      "type":"library",
	//      "version":"5.2.2.RELEASE"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.springframework.security/spring-security-config@5.2.1.RELEASE?type=jar",
	//      "name":"spring-security-config",
	//      "purl":"pkg:maven/org.springframework.security/spring-security-config@5.2.1.RELEASE?type=jar",
	//      "type":"library",
	//      "version":"5.2.1.RELEASE"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.springframework.data/spring-data-jpa@2.2.3.RELEASE?type=jar",
	//      "name":"spring-data-jpa",
	//      "purl":"pkg:maven/org.springframework.data/spring-data-jpa@2.2.3.RELEASE?type=jar",
	//      "type":"library",
	//      "version":"2.2.3.RELEASE"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.springframework.boot/spring-boot-starter-undertow@2.2.2.RELEASE?type=jar",
	//      "name":"spring-boot-starter-undertow",
	//      "purl":"pkg:maven/org.springframework.boot/spring-boot-starter-undertow@2.2.2.RELEASE?type=jar",
	//      "type":"library",
	//      "version":"2.2.2.RELEASE"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.apache.ant/ant@1.6.2?type=jar",
	//      "name":"ant",
	//      "purl":"pkg:maven/org.apache.ant/ant@1.6.2?type=jar",
	//      "type":"library",
	//      "version":"1.6.2"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.springframework.boot/spring-boot-actuator@2.2.2.RELEASE?type=jar",
	//      "name":"spring-boot-actuator",
	//      "purl":"pkg:maven/org.springframework.boot/spring-boot-actuator@2.2.2.RELEASE?type=jar",
	//      "type":"library",
	//      "version":"2.2.2.RELEASE"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/jakarta.xml.bind/jakarta.xml.bind-api@2.3.2?type=jar",
	//      "name":"jakarta.xml.bind-api",
	//      "purl":"pkg:maven/jakarta.xml.bind/jakarta.xml.bind-api@2.3.2?type=jar",
	//      "type":"library",
	//      "version":"2.3.2"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.owasp.webgoat.lesson/missing-function-ac@8.1.0?type=jar",
	//      "name":"missing-function-ac",
	//      "purl":"pkg:maven/org.owasp.webgoat.lesson/missing-function-ac@8.1.0?type=jar",
	//      "type":"library",
	//      "version":"8.1.0"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.springframework.boot/spring-boot-starter-web@2.2.2.RELEASE?type=jar",
	//      "name":"spring-boot-starter-web",
	//      "purl":"pkg:maven/org.springframework.boot/spring-boot-starter-web@2.2.2.RELEASE?type=jar",
	//      "type":"library",
	//      "version":"2.2.2.RELEASE"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.springframework/spring-context@5.2.2.RELEASE?type=jar",
	//      "name":"spring-context",
	//      "purl":"pkg:maven/org.springframework/spring-context@5.2.2.RELEASE?type=jar",
	//      "type":"library",
	//      "version":"5.2.2.RELEASE"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.springframework.boot/spring-boot-starter-thymeleaf@2.2.2.RELEASE?type=jar",
	//      "name":"spring-boot-starter-thymeleaf",
	//      "purl":"pkg:maven/org.springframework.boot/spring-boot-starter-thymeleaf@2.2.2.RELEASE?type=jar",
	//      "type":"library",
	//      "version":"2.2.2.RELEASE"
	//    },
	//    {
	//      "bom-ref":"pkg:maven//xpp3_min@1.1.4c?type=jar",
	//      "name":"xpp3_min",
	//      "purl":"pkg:maven//xpp3_min@1.1.4c?type=jar",
	//      "type":"library",
	//      "version":"1.1.4c"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.glassfish/jakarta.el@3.0.3?type=jar",
	//      "name":"jakarta.el",
	//      "purl":"pkg:maven/org.glassfish/jakarta.el@3.0.3?type=jar",
	//      "type":"library",
	//      "version":"3.0.3"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/com.fasterxml.jackson.core/jackson-annotations@2.10.1?type=jar",
	//      "name":"jackson-annotations",
	//      "purl":"pkg:maven/com.fasterxml.jackson.core/jackson-annotations@2.10.1?type=jar",
	//      "type":"library",
	//      "version":"2.10.1"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.owasp.webgoat.lesson/chrome-dev-tools@8.1.0?type=jar",
	//      "name":"chrome-dev-tools",
	//      "purl":"pkg:maven/org.owasp.webgoat.lesson/chrome-dev-tools@8.1.0?type=jar",
	//      "type":"library",
	//      "version":"8.1.0"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.yaml/snakeyaml@1.25?type=jar",
	//      "name":"snakeyaml",
	//      "purl":"pkg:maven/org.yaml/snakeyaml@1.25?type=jar",
	//      "type":"library",
	//      "version":"1.25"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/io.jsonwebtoken/jjwt@0.7.0?type=jar",
	//      "name":"jjwt",
	//      "purl":"pkg:maven/io.jsonwebtoken/jjwt@0.7.0?type=jar",
	//      "type":"library",
	//      "version":"0.7.0"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.owasp.webgoat.lesson/jwt@8.1.0?type=jar",
	//      "name":"jwt",
	//      "purl":"pkg:maven/org.owasp.webgoat.lesson/jwt@8.1.0?type=jar",
	//      "type":"library",
	//      "version":"8.1.0"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.owasp.webgoat.lesson/challenge@8.1.0?type=jar",
	//      "name":"challenge",
	//      "purl":"pkg:maven/org.owasp.webgoat.lesson/challenge@8.1.0?type=jar",
	//      "type":"library",
	//      "version":"8.1.0"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.javassist/javassist@3.24.0-GA?type=jar",
	//      "name":"javassist",
	//      "purl":"pkg:maven/org.javassist/javassist@3.24.0-GA?type=jar",
	//      "type":"library",
	//      "version":"3.24.0-GA"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.jboss/jandex@2.1.1.Final?type=jar",
	//      "name":"jandex",
	//      "purl":"pkg:maven/org.jboss/jandex@2.1.1.Final?type=jar",
	//      "type":"library",
	//      "version":"2.1.1.Final"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/jakarta.transaction/jakarta.transaction-api@1.3.3?type=jar",
	//      "name":"jakarta.transaction-api",
	//      "purl":"pkg:maven/jakarta.transaction/jakarta.transaction-api@1.3.3?type=jar",
	//      "type":"library",
	//      "version":"1.3.3"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.owasp.webgoat.lesson/crypto@8.1.0?type=jar",
	//      "name":"crypto",
	//      "purl":"pkg:maven/org.owasp.webgoat.lesson/crypto@8.1.0?type=jar",
	//      "type":"library",
	//      "version":"8.1.0"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.springframework.boot/spring-boot-starter-actuator@2.2.2.RELEASE?type=jar",
	//      "name":"spring-boot-starter-actuator",
	//      "purl":"pkg:maven/org.springframework.boot/spring-boot-starter-actuator@2.2.2.RELEASE?type=jar",
	//      "type":"library",
	//      "version":"2.2.2.RELEASE"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.owasp.webgoat.lesson/html-tampering@8.1.0?type=jar",
	//      "name":"html-tampering",
	//      "purl":"pkg:maven/org.owasp.webgoat.lesson/html-tampering@8.1.0?type=jar",
	//      "type":"library",
	//      "version":"8.1.0"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/ch.qos.logback/logback-classic@1.2.3?type=jar",
	//      "name":"logback-classic",
	//      "purl":"pkg:maven/ch.qos.logback/logback-classic@1.2.3?type=jar",
	//      "type":"library",
	//      "version":"1.2.3"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.latencyutils/LatencyUtils@2.0.3?type=jar",
	//      "name":"LatencyUtils",
	//      "purl":"pkg:maven/org.latencyutils/LatencyUtils@2.0.3?type=jar",
	//      "type":"library",
	//      "version":"2.0.3"
	//    },
	//    {
	//      "bom-ref":"pkg:maven//path-traversal@8.1.0?type=jar",
	//      "name":"path-traversal",
	//      "purl":"pkg:maven//path-traversal@8.1.0?type=jar",
	//      "type":"library",
	//      "version":"8.1.0"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.springframework/spring-tx@5.2.2.RELEASE?type=jar",
	//      "name":"spring-tx",
	//      "purl":"pkg:maven/org.springframework/spring-tx@5.2.2.RELEASE?type=jar",
	//      "type":"library",
	//      "version":"5.2.2.RELEASE"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.hibernate.validator/hibernate-validator@6.0.18.Final?type=jar",
	//      "name":"hibernate-validator",
	//      "purl":"pkg:maven/org.hibernate.validator/hibernate-validator@6.0.18.Final?type=jar",
	//      "type":"library",
	//      "version":"6.0.18.Final"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/com.sun.istack/istack-commons-runtime@3.0.8?type=jar",
	//      "name":"istack-commons-runtime",
	//      "purl":"pkg:maven/com.sun.istack/istack-commons-runtime@3.0.8?type=jar",
	//      "type":"library",
	//      "version":"3.0.8"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.owasp.webgoat.lesson/ssrf@8.1.0?type=jar",
	//      "name":"ssrf",
	//      "purl":"pkg:maven/org.owasp.webgoat.lesson/ssrf@8.1.0?type=jar",
	//      "type":"library",
	//      "version":"8.1.0"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/com.fasterxml.jackson.datatype/jackson-datatype-jdk8@2.10.1?type=jar",
	//      "name":"jackson-datatype-jdk8",
	//      "purl":"pkg:maven/com.fasterxml.jackson.datatype/jackson-datatype-jdk8@2.10.1?type=jar",
	//      "type":"library",
	//      "version":"2.10.1"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.owasp.webgoat.lesson/http-proxies@8.1.0?type=jar",
	//      "name":"http-proxies",
	//      "purl":"pkg:maven/org.owasp.webgoat.lesson/http-proxies@8.1.0?type=jar",
	//      "type":"library",
	//      "version":"8.1.0"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.owasp.webgoat.lesson/sql-injection@8.1.0?type=jar",
	//      "name":"sql-injection",
	//      "purl":"pkg:maven/org.owasp.webgoat.lesson/sql-injection@8.1.0?type=jar",
	//      "type":"library",
	//      "version":"8.1.0"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.pcollections/pcollections@3.1.0?type=jar",
	//      "name":"pcollections",
	//      "purl":"pkg:maven/org.pcollections/pcollections@3.1.0?type=jar",
	//      "type":"library",
	//      "version":"3.1.0"
	//    },
	//    {
	//      "bom-ref":"pkg:maven//xml-resolver@1.2?type=jar",
	//      "name":"xml-resolver",
	//      "purl":"pkg:maven//xml-resolver@1.2?type=jar",
	//      "type":"library",
	//      "version":"1.2"
	//    },
	//    {
	//      "bom-ref":"pkg:maven//xmlpull@1.1.3.1?type=jar",
	//      "name":"xmlpull",
	//      "purl":"pkg:maven//xmlpull@1.1.3.1?type=jar",
	//      "type":"library",
	//      "version":"1.1.3.1"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.hdrhistogram/HdrHistogram@2.1.11?type=jar",
	//      "name":"HdrHistogram",
	//      "purl":"pkg:maven/org.hdrhistogram/HdrHistogram@2.1.11?type=jar",
	//      "type":"library",
	//      "version":"2.1.11"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.springframework.boot/spring-boot-starter-logging@2.2.2.RELEASE?type=jar",
	//      "name":"spring-boot-starter-logging",
	//      "purl":"pkg:maven/org.springframework.boot/spring-boot-starter-logging@2.2.2.RELEASE?type=jar",
	//      "type":"library",
	//      "version":"2.2.2.RELEASE"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/io.undertow/undertow-core@2.0.28.Final?type=jar",
	//      "name":"undertow-core",
	//      "purl":"pkg:maven/io.undertow/undertow-core@2.0.28.Final?type=jar",
	//      "type":"library",
	//      "version":"2.0.28.Final"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.owasp.webgoat.lesson/webgoat-lesson-template@8.1.0?type=jar",
	//      "name":"webgoat-lesson-template",
	//      "purl":"pkg:maven/org.owasp.webgoat.lesson/webgoat-lesson-template@8.1.0?type=jar",
	//      "type":"library",
	//      "version":"8.1.0"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.hibernate.common.hibernate-commons-annotation/hibernate-commons-annotations@5.1.0.Final?type=jar",
	//      "name":"hibernate-commons-annotations",
	//      "purl":"pkg:maven/org.hibernate.common.hibernate-commons-annotation/hibernate-commons-annotations@5.1.0.Final?type=jar",
	//      "type":"library",
	//      "version":"5.1.0.Final"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.springframework/spring-jcl@5.2.2.RELEASE?type=jar",
	//      "name":"spring-jcl",
	//      "purl":"pkg:maven/org.springframework/spring-jcl@5.2.2.RELEASE?type=jar",
	//      "type":"library",
	//      "version":"5.2.2.RELEASE"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.dom4j/dom4j@2.1.1?type=jar",
	//      "name":"dom4j",
	//      "purl":"pkg:maven/org.dom4j/dom4j@2.1.1?type=jar",
	//      "type":"library",
	//      "version":"2.1.1"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/com.fasterxml.jackson.core/jackson-databind@2.10.1?type=jar",
	//      "name":"jackson-databind",
	//      "purl":"pkg:maven/com.fasterxml.jackson.core/jackson-databind@2.10.1?type=jar",
	//      "type":"library",
	//      "version":"2.10.1"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.thymeleaf.extras/thymeleaf-extras-java8time@3.0.4.RELEASE?type=jar",
	//      "name":"thymeleaf-extras-java8time",
	//      "purl":"pkg:maven/org.thymeleaf.extras/thymeleaf-extras-java8time@3.0.4.RELEASE?type=jar",
	//      "type":"library",
	//      "version":"3.0.4.RELEASE"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/com.fasterxml.jackson.core/jackson-core@2.10.1?type=jar",
	//      "name":"jackson-core",
	//      "purl":"pkg:maven/com.fasterxml.jackson.core/jackson-core@2.10.1?type=jar",
	//      "type":"library",
	//      "version":"2.10.1"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/jakarta.activation/jakarta.activation-api@1.2.1?type=jar",
	//      "name":"jakarta.activation-api",
	//      "purl":"pkg:maven/jakarta.activation/jakarta.activation-api@1.2.1?type=jar",
	//      "type":"library",
	//      "version":"1.2.1"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.apache.commons/commons-exec@1.3?type=jar",
	//      "name":"commons-exec",
	//      "purl":"pkg:maven/org.apache.commons/commons-exec@1.3?type=jar",
	//      "type":"library",
	//      "version":"1.3"
	//    },
	//    {
	//      "bom-ref":"pkg:maven//ant-launcher@1.6.2?type=jar",
	//      "name":"ant-launcher",
	//      "purl":"pkg:maven//ant-launcher@1.6.2?type=jar",
	//      "type":"library",
	//      "version":"1.6.2"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.springframework/spring-webmvc@5.2.2.RELEASE?type=jar",
	//      "name":"spring-webmvc",
	//      "purl":"pkg:maven/org.springframework/spring-webmvc@5.2.2.RELEASE?type=jar",
	//      "type":"library",
	//      "version":"5.2.2.RELEASE"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.projectlombok/lombok@1.18.4?type=jar",
	//      "name":"lombok",
	//      "purl":"pkg:maven/org.projectlombok/lombok@1.18.4?type=jar",
	//      "type":"library",
	//      "version":"1.18.4"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.slf4j/slf4j-api@1.7.29?type=jar",
	//      "name":"slf4j-api",
	//      "purl":"pkg:maven/org.slf4j/slf4j-api@1.7.29?type=jar",
	//      "type":"library",
	//      "version":"1.7.29"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/jakarta.validation/jakarta.validation-api@2.0.1?type=jar",
	//      "name":"jakarta.validation-api",
	//      "purl":"pkg:maven/jakarta.validation/jakarta.validation-api@2.0.1?type=jar",
	//      "type":"library",
	//      "version":"2.0.1"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.owasp.webgoat.lesson/cia@8.1.0?type=jar",
	//      "name":"cia",
	//      "purl":"pkg:maven/org.owasp.webgoat.lesson/cia@8.1.0?type=jar",
	//      "type":"library",
	//      "version":"8.1.0"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.jruby/jruby-complete@9.1.17.0?type=jar",
	//      "name":"jruby-complete",
	//      "purl":"pkg:maven/org.jruby/jruby-complete@9.1.17.0?type=jar",
	//      "type":"library",
	//      "version":"9.1.17.0"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.apache.commons/commons-lang3@3.4?type=jar",
	//      "name":"commons-lang3",
	//      "purl":"pkg:maven/org.apache.commons/commons-lang3@3.4?type=jar",
	//      "type":"library",
	//      "version":"3.4"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/com.sun.xml.fastinfoset/FastInfoset@1.2.16?type=jar",
	//      "name":"FastInfoset",
	//      "purl":"pkg:maven/com.sun.xml.fastinfoset/FastInfoset@1.2.16?type=jar",
	//      "type":"library",
	//      "version":"1.2.16"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.jboss.xnio/xnio-nio@3.3.8.Final?type=jar",
	//      "name":"xnio-nio",
	//      "purl":"pkg:maven/org.jboss.xnio/xnio-nio@3.3.8.Final?type=jar",
	//      "type":"library",
	//      "version":"3.3.8.Final"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.springframework/spring-expression@5.2.2.RELEASE?type=jar",
	//      "name":"spring-expression",
	//      "purl":"pkg:maven/org.springframework/spring-expression@5.2.2.RELEASE?type=jar",
	//      "type":"library",
	//      "version":"5.2.2.RELEASE"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.jboss.logging/jboss-logging@3.4.1.Final?type=jar",
	//      "name":"jboss-logging",
	//      "purl":"pkg:maven/org.jboss.logging/jboss-logging@3.4.1.Final?type=jar",
	//      "type":"library",
	//      "version":"3.4.1.Final"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.springframework.boot/spring-boot-starter-aop@2.2.2.RELEASE?type=jar",
	//      "name":"spring-boot-starter-aop",
	//      "purl":"pkg:maven/org.springframework.boot/spring-boot-starter-aop@2.2.2.RELEASE?type=jar",
	//      "type":"library",
	//      "version":"2.2.2.RELEASE"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.jboss.spec.javax.annotation/jboss-annotations-api_1.2_spec@1.0.2.Final?type=jar",
	//      "name":"jboss-annotations-api_1.2_spec",
	//      "purl":"pkg:maven/org.jboss.spec.javax.annotation/jboss-annotations-api_1.2_spec@1.0.2.Final?type=jar",
	//      "type":"library",
	//      "version":"1.0.2.Final"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/ch.qos.logback/logback-core@1.2.3?type=jar",
	//      "name":"logback-core",
	//      "purl":"pkg:maven/ch.qos.logback/logback-core@1.2.3?type=jar",
	//      "type":"library",
	//      "version":"1.2.3"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.owasp.webgoat.lesson/insecure-deserialization@8.1.0?type=jar",
	//      "name":"insecure-deserialization",
	//      "purl":"pkg:maven/org.owasp.webgoat.lesson/insecure-deserialization@8.1.0?type=jar",
	//      "type":"library",
	//      "version":"8.1.0"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.jsoup/jsoup@1.11.3?type=jar",
	//      "name":"jsoup",
	//      "purl":"pkg:maven/org.jsoup/jsoup@1.11.3?type=jar",
	//      "type":"library",
	//      "version":"1.11.3"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.owasp.webgoat.lesson/client-side-filtering@8.1.0?type=jar",
	//      "name":"client-side-filtering",
	//      "purl":"pkg:maven/org.owasp.webgoat.lesson/client-side-filtering@8.1.0?type=jar",
	//      "type":"library",
	//      "version":"8.1.0"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/com.fasterxml.jackson.module/jackson-module-parameter-names@2.10.1?type=jar",
	//      "name":"jackson-module-parameter-names",
	//      "purl":"pkg:maven/com.fasterxml.jackson.module/jackson-module-parameter-names@2.10.1?type=jar",
	//      "type":"library",
	//      "version":"2.10.1"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.springframework.security/spring-security-web@5.2.1.RELEASE?type=jar",
	//      "name":"spring-security-web",
	//      "purl":"pkg:maven/org.springframework.security/spring-security-web@5.2.1.RELEASE?type=jar",
	//      "type":"library",
	//      "version":"5.2.1.RELEASE"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/com.fasterxml/classmate@1.5.1?type=jar",
	//      "name":"classmate",
	//      "purl":"pkg:maven/com.fasterxml/classmate@1.5.1?type=jar",
	//      "type":"library",
	//      "version":"1.5.1"
	//    },
	//    {
	//      "bom-ref":"pkg:maven/org.owasp.webgoat.lesson/webwolf-introduction@8.1.0?type=jar",
	//      "name":"webwolf-introduction",
	//      "purl":"pkg:maven/org.owasp.webgoat.lesson/webwolf-introduction@8.1.0?type=jar",
	//      "type":"library",
	//      "version":"8.1.0"
	//    }
	//  ],
	//  "metadata":{
	//    "timestamp":"2022-08-12T08:03:30.459054+00:00",
	//    "tools":[
	//      {
	//        "name":"SDA",
	//        "vendor":"****",
	//        "version":"v7.0"
	//      }
	//    ]
	//  },
	//  "serialNumber":"urn:uuid:bf6ceb1f-3cfc-4475-be23-656ac8b34002",
	//  "specVersion":"1.4",
	//  "version":1,
	//  "vulnerabilities":[ ]
	//}`
	py_sbom := "{\n  \"$schema\":\"http://cyclonedx.org/schema/bom-1.4.schema.json\",\n  \"bomFormat\":\"CycloneDX\",\n  \"components\":[\n    {\n      \"bom-ref\":\"pkg:pypi/setuptools@18.1\",\n      \"name\":\"setuptools\",\n      \"purl\":\"pkg:pypi/setuptools@18.1\",\n      \"type\":\"library\",\n      \"version\":\"18.1\"\n    },\n    {\n      \"bom-ref\":\"pkg:pypi/celery@3.1.19\",\n      \"name\":\"celery\",\n      \"purl\":\"pkg:pypi/celery@3.1.19\",\n      \"type\":\"library\",\n      \"version\":\"3.1.19\"\n    },\n    {\n      \"bom-ref\":\"pkg:pypi/kombu@3.0.37\",\n      \"name\":\"kombu\",\n      \"purl\":\"pkg:pypi/kombu@3.0.37\",\n      \"type\":\"library\",\n      \"version\":\"3.0.37\"\n    },\n    {\n      \"bom-ref\":\"pkg:pypi/billiard@3.3.0.23\",\n      \"name\":\"billiard\",\n      \"purl\":\"pkg:pypi/billiard@3.3.0.23\",\n      \"type\":\"library\",\n      \"version\":\"3.3.0.23\"\n    },\n    {\n      \"bom-ref\":\"pkg:pypi/pytz@2019.1\",\n      \"name\":\"pytz\",\n      \"purl\":\"pkg:pypi/pytz@2019.1\",\n      \"type\":\"library\",\n      \"version\":\"2019.1\"\n    },\n    {\n      \"bom-ref\":\"pkg:pypi/amqp@1.4.9\",\n      \"name\":\"amqp\",\n      \"purl\":\"pkg:pypi/amqp@1.4.9\",\n      \"type\":\"library\",\n      \"version\":\"1.4.9\"\n    },\n    {\n      \"bom-ref\":\"pkg:pypi/anyjson@0.3.3\",\n      \"name\":\"anyjson\",\n      \"purl\":\"pkg:pypi/anyjson@0.3.3\",\n      \"type\":\"library\",\n      \"version\":\"0.3.3\"\n    },\n    {\n      \"bom-ref\":\"pkg:pypi/celery-with-redis@3.0\",\n      \"name\":\"celery-with-redis\",\n      \"purl\":\"pkg:pypi/celery-with-redis@3.0\",\n      \"type\":\"library\",\n      \"version\":\"3.0\"\n    },\n    {\n      \"bom-ref\":\"pkg:pypi/redis@3.2.1\",\n      \"name\":\"redis\",\n      \"purl\":\"pkg:pypi/redis@3.2.1\",\n      \"type\":\"library\",\n      \"version\":\"3.2.1\"\n    },\n    {\n      \"bom-ref\":\"pkg:pypi/crypto@1.4.1\",\n      \"name\":\"crypto\",\n      \"purl\":\"pkg:pypi/crypto@1.4.1\",\n      \"type\":\"library\",\n      \"version\":\"1.4.1\"\n    },\n    {\n      \"bom-ref\":\"pkg:pypi/shellescape@3.4.1\",\n      \"name\":\"shellescape\",\n      \"purl\":\"pkg:pypi/shellescape@3.4.1\",\n      \"type\":\"library\",\n      \"version\":\"3.4.1\"\n    },\n    {\n      \"bom-ref\":\"pkg:pypi/naked@0.1.31\",\n      \"name\":\"naked\",\n      \"purl\":\"pkg:pypi/naked@0.1.31\",\n      \"type\":\"library\",\n      \"version\":\"0.1.31\"\n    },\n    {\n      \"bom-ref\":\"pkg:pypi/pyyaml@5.1\",\n      \"name\":\"pyyaml\",\n      \"purl\":\"pkg:pypi/pyyaml@5.1\",\n      \"type\":\"library\",\n      \"version\":\"5.1\"\n    },\n    {\n      \"bom-ref\":\"pkg:pypi/certifi@2019.3.9\",\n      \"name\":\"certifi\",\n      \"purl\":\"pkg:pypi/certifi@2019.3.9\",\n      \"type\":\"library\",\n      \"version\":\"2019.3.9\"\n    },\n    {\n      \"bom-ref\":\"pkg:pypi/urllib3@1.24.1\",\n      \"name\":\"urllib3\",\n      \"purl\":\"pkg:pypi/urllib3@1.24.1\",\n      \"type\":\"library\",\n      \"version\":\"1.24.1\"\n    },\n    {\n      \"bom-ref\":\"pkg:pypi/idna@2.8\",\n      \"name\":\"idna\",\n      \"purl\":\"pkg:pypi/idna@2.8\",\n      \"type\":\"library\",\n      \"version\":\"2.8\"\n    },\n    {\n      \"bom-ref\":\"pkg:pypi/chardet@3.0.4\",\n      \"name\":\"chardet\",\n      \"purl\":\"pkg:pypi/chardet@3.0.4\",\n      \"type\":\"library\",\n      \"version\":\"3.0.4\"\n    },\n    {\n      \"bom-ref\":\"pkg:pypi/django@1.8.2\",\n      \"name\":\"django\",\n      \"purl\":\"pkg:pypi/django@1.8.2\",\n      \"type\":\"library\",\n      \"version\":\"1.8.2\"\n    },\n    {\n      \"bom-ref\":\"pkg:pypi/djangorestframework@3.3.1\",\n      \"name\":\"djangorestframework\",\n      \"purl\":\"pkg:pypi/djangorestframework@3.3.1\",\n      \"type\":\"library\",\n      \"version\":\"3.3.1\"\n    },\n    {\n      \"bom-ref\":\"pkg:pypi/ecdsa@0.13\",\n      \"name\":\"ecdsa\",\n      \"purl\":\"pkg:pypi/ecdsa@0.13\",\n      \"type\":\"library\",\n      \"version\":\"0.13\"\n    },\n    {\n      \"bom-ref\":\"pkg:pypi/fonts@0.0.3\",\n      \"name\":\"fonts\",\n      \"purl\":\"pkg:pypi/fonts@0.0.3\",\n      \"type\":\"library\",\n      \"version\":\"0.0.3\"\n    },\n    {\n      \"bom-ref\":\"pkg:pypi/jinja2@2.8\",\n      \"name\":\"jinja2\",\n      \"purl\":\"pkg:pypi/jinja2@2.8\",\n      \"type\":\"library\",\n      \"version\":\"2.8\"\n    },\n    {\n      \"bom-ref\":\"pkg:pypi/markupsafe@1.1.1\",\n      \"name\":\"markupsafe\",\n      \"purl\":\"pkg:pypi/markupsafe@1.1.1\",\n      \"type\":\"library\",\n      \"version\":\"1.1.1\"\n    },\n    {\n      \"bom-ref\":\"pkg:pypi/six@1.12.0\",\n      \"name\":\"six\",\n      \"purl\":\"pkg:pypi/six@1.12.0\",\n      \"type\":\"library\",\n      \"version\":\"1.12.0\"\n    },\n    {\n      \"bom-ref\":\"pkg:pypi/kazoo@2.6.1\",\n      \"name\":\"kazoo\",\n      \"purl\":\"pkg:pypi/kazoo@2.6.1\",\n      \"type\":\"library\",\n      \"version\":\"2.6.1\"\n    },\n    {\n      \"bom-ref\":\"pkg:pypi/lxml@3.4.4\",\n      \"name\":\"lxml\",\n      \"purl\":\"pkg:pypi/lxml@3.4.4\",\n      \"type\":\"library\",\n      \"version\":\"3.4.4\"\n    },\n    {\n      \"bom-ref\":\"pkg:pypi/paramiko@1.15.1\",\n      \"name\":\"paramiko\",\n      \"purl\":\"pkg:pypi/paramiko@1.15.1\",\n      \"type\":\"library\",\n      \"version\":\"1.15.1\"\n    },\n    {\n      \"bom-ref\":\"pkg:pypi/pycrypto@2.6.1\",\n      \"name\":\"pycrypto\",\n      \"purl\":\"pkg:pypi/pycrypto@2.6.1\",\n      \"type\":\"library\",\n      \"version\":\"2.6.1\"\n    },\n    {\n      \"bom-ref\":\"pkg:pypi/psycopg2@2.7.7\",\n      \"name\":\"psycopg2\",\n      \"purl\":\"pkg:pypi/psycopg2@2.7.7\",\n      \"type\":\"library\",\n      \"version\":\"2.7.7\"\n    },\n    {\n      \"bom-ref\":\"pkg:pypi/pyhs2@0.6.0\",\n      \"name\":\"pyhs2\",\n      \"purl\":\"pkg:pypi/pyhs2@0.6.0\",\n      \"type\":\"library\",\n      \"version\":\"0.6.0\"\n    },\n    {\n      \"bom-ref\":\"pkg:pypi/sasl@0.2.1\",\n      \"name\":\"sasl\",\n      \"purl\":\"pkg:pypi/sasl@0.2.1\",\n      \"type\":\"library\",\n      \"version\":\"0.2.1\"\n    },\n    {\n      \"bom-ref\":\"pkg:pypi/requests@2.9.1\",\n      \"name\":\"requests\",\n      \"purl\":\"pkg:pypi/requests@2.9.1\",\n      \"type\":\"library\",\n      \"version\":\"2.9.1\"\n    },\n    {\n      \"bom-ref\":\"pkg:pypi/shortuuid@0.5.0\",\n      \"name\":\"shortuuid\",\n      \"purl\":\"pkg:pypi/shortuuid@0.5.0\",\n      \"type\":\"library\",\n      \"version\":\"0.5.0\"\n    },\n    {\n      \"bom-ref\":\"pkg:pypi/sqlalchemy@1.0.1\",\n      \"name\":\"sqlalchemy\",\n      \"purl\":\"pkg:pypi/sqlalchemy@1.0.1\",\n      \"type\":\"library\",\n      \"version\":\"1.0.1\"\n    },\n    {\n      \"bom-ref\":\"pkg:pypi/ssh@1.8.0\",\n      \"name\":\"ssh\",\n      \"purl\":\"pkg:pypi/ssh@1.8.0\",\n      \"type\":\"library\",\n      \"version\":\"1.8.0\"\n    },\n    {\n      \"bom-ref\":\"pkg:pypi/thrift@0.9.2\",\n      \"name\":\"thrift\",\n      \"purl\":\"pkg:pypi/thrift@0.9.2\",\n      \"type\":\"library\",\n      \"version\":\"0.9.2\"\n    },\n    {\n      \"bom-ref\":\"pkg:pypi/xlrd@1.2.0\",\n      \"name\":\"xlrd\",\n      \"purl\":\"pkg:pypi/xlrd@1.2.0\",\n      \"type\":\"library\",\n      \"version\":\"1.2.0\"\n    },\n    {\n      \"bom-ref\":\"pkg:pypi/xlutils@2.0.0\",\n      \"name\":\"xlutils\",\n      \"purl\":\"pkg:pypi/xlutils@2.0.0\",\n      \"type\":\"library\",\n      \"version\":\"2.0.0\"\n    },\n    {\n      \"bom-ref\":\"pkg:pypi/xlwt@1.0.0\",\n      \"name\":\"xlwt\",\n      \"purl\":\"pkg:pypi/xlwt@1.0.0\",\n      \"type\":\"library\",\n      \"version\":\"1.0.0\"\n    },\n    {\n      \"bom-ref\":\"pkg:pypi/pillow@6.0.0\",\n      \"name\":\"pillow\",\n      \"purl\":\"pkg:pypi/pillow@6.0.0\",\n      \"type\":\"library\",\n      \"version\":\"6.0.0\"\n    },\n    {\n      \"bom-ref\":\"pkg:pypi/elasticsearch@6.4.0\",\n      \"name\":\"elasticsearch\",\n      \"purl\":\"pkg:pypi/elasticsearch@6.4.0\",\n      \"type\":\"library\",\n      \"version\":\"6.4.0\"\n    },\n    {\n      \"bom-ref\":\"pkg:pypi/django-redis@4.7.0\",\n      \"name\":\"django-redis\",\n      \"purl\":\"pkg:pypi/django-redis@4.7.0\",\n      \"type\":\"library\",\n      \"version\":\"4.7.0\"\n    },\n    {\n      \"bom-ref\":\"pkg:pypi/pip@10.0.1\",\n      \"name\":\"pip\",\n      \"purl\":\"pkg:pypi/pip@10.0.1\",\n      \"type\":\"library\",\n      \"version\":\"10.0.1\"\n    },\n    {\n      \"bom-ref\":\"pkg:pypi/wsgiref@0.1.2\",\n      \"name\":\"wsgiref\",\n      \"purl\":\"pkg:pypi/wsgiref@0.1.2\",\n      \"type\":\"library\",\n      \"version\":\"0.1.2\"\n    },\n    {\n      \"bom-ref\":\"pkg:pypi/python@2.7.10\",\n      \"name\":\"python\",\n      \"purl\":\"pkg:pypi/python@2.7.10\",\n      \"type\":\"library\",\n      \"version\":\"2.7.10\"\n    },\n    {\n      \"bom-ref\":\"pkg:pypi/webob@1.8.7\",\n      \"name\":\"webob\",\n      \"purl\":\"pkg:pypi/webob@1.8.7\",\n      \"type\":\"library\",\n      \"version\":\"1.8.7\"\n    },\n    {\n      \"bom-ref\":\"pkg:pypi/kafka@1.3.5\",\n      \"name\":\"kafka\",\n      \"purl\":\"pkg:pypi/kafka@1.3.5\",\n      \"type\":\"library\",\n      \"version\":\"1.3.5\"\n    },\n    {\n      \"bom-ref\":\"pkg:pypi/uwsgi@2.0.18\",\n      \"name\":\"uwsgi\",\n      \"purl\":\"pkg:pypi/uwsgi@2.0.18\",\n      \"type\":\"library\",\n      \"version\":\"2.0.18\"\n    },\n    {\n      \"bom-ref\":\"pkg:pypi/docopt@0.6.2\",\n      \"name\":\"docopt\",\n      \"purl\":\"pkg:pypi/docopt@0.6.2\",\n      \"type\":\"library\",\n      \"version\":\"0.6.2\"\n    },\n    {\n      \"bom-ref\":\"pkg:pypi/mlogging@0.1\",\n      \"name\":\"mlogging\",\n      \"purl\":\"pkg:pypi/mlogging@0.1\",\n      \"type\":\"library\",\n      \"version\":\"0.1\"\n    },\n    {\n      \"bom-ref\":\"pkg:pypi/openpyxl@2.6.4\",\n      \"name\":\"openpyxl\",\n      \"purl\":\"pkg:pypi/openpyxl@2.6.4\",\n      \"type\":\"library\",\n      \"version\":\"2.6.4\"\n    },\n    {\n      \"bom-ref\":\"pkg:pypi/pexpect@2.3\",\n      \"name\":\"pexpect\",\n      \"purl\":\"pkg:pypi/pexpect@2.3\",\n      \"type\":\"library\",\n      \"version\":\"2.3\"\n    },\n    {\n      \"bom-ref\":\"pkg:pypi/decorator@4.4.2\",\n      \"name\":\"decorator\",\n      \"purl\":\"pkg:pypi/decorator@4.4.2\",\n      \"type\":\"library\",\n      \"version\":\"4.4.2\"\n    },\n    {\n      \"bom-ref\":\"pkg:pypi/ryze-agent-python@1.1.0\",\n      \"name\":\"ryze-agent-python\",\n      \"purl\":\"pkg:pypi/ryze-agent-python@1.1.0\",\n      \"type\":\"library\",\n      \"version\":\"1.1.0\"\n    },\n    {\n      \"bom-ref\":\"pkg:pypi/pipreqs@0.4.10\",\n      \"name\":\"pipreqs\",\n      \"purl\":\"pkg:pypi/pipreqs@0.4.10\",\n      \"type\":\"library\",\n      \"version\":\"0.4.10\"\n    },\n    {\n      \"bom-ref\":\"pkg:pypi/typing@3.7.4.3\",\n      \"name\":\"typing\",\n      \"purl\":\"pkg:pypi/typing@3.7.4.3\",\n      \"type\":\"library\",\n      \"version\":\"3.7.4.3\"\n    },\n    {\n      \"bom-ref\":\"pkg:pypi/wheel@0.37.1\",\n      \"name\":\"wheel\",\n      \"purl\":\"pkg:pypi/wheel@0.37.1\",\n      \"type\":\"library\",\n      \"version\":\"0.37.1\"\n    },\n    {\n      \"bom-ref\":\"pkg:pypi/pyprotect@1.0\",\n      \"name\":\"pyprotect\",\n      \"purl\":\"pkg:pypi/pyprotect@1.0\",\n      \"type\":\"library\",\n      \"version\":\"1.0\"\n    },\n    {\n      \"bom-ref\":\"pkg:pypi/jdcal@1.4.1\",\n      \"name\":\"jdcal\",\n      \"purl\":\"pkg:pypi/jdcal@1.4.1\",\n      \"type\":\"library\",\n      \"version\":\"1.4.1\"\n    },\n    {\n      \"bom-ref\":\"pkg:pypi/yarg@0.1.9\",\n      \"name\":\"yarg\",\n      \"purl\":\"pkg:pypi/yarg@0.1.9\",\n      \"type\":\"library\",\n      \"version\":\"0.1.9\"\n    },\n    {\n      \"bom-ref\":\"pkg:pypi/et-xmlfile@1.0.1\",\n      \"name\":\"et-xmlfile\",\n      \"purl\":\"pkg:pypi/et-xmlfile@1.0.1\",\n      \"type\":\"library\",\n      \"version\":\"1.0.1\"\n    },\n    {\n      \"bom-ref\":\"pkg:pypi/pil@1.1.7\",\n      \"name\":\"pil\",\n      \"purl\":\"pkg:pypi/pil@1.1.7\",\n      \"type\":\"library\",\n      \"version\":\"1.1.7\"\n    }\n  ],\n  \"metadata\":{\n    \"timestamp\":\"2022-08-12T08:03:30.459054+00:00\",\n    \"tools\":[\n      {\n        \"name\":\"SDA\",\n        \"vendor\":\"****\",\n        \"version\":\"v7.0\"\n      }\n    ]\n  },\n  \"serialNumber\":\"urn:uuid:bf6ceb1f-3cfc-4475-be23-656ac8b34002\",\n  \"specVersion\":\"1.4\",\n  \"version\":1,\n  \"vulnerabilities\":[ ]\n}"
	Rpc(py_sbom)
}

// 调用sca分析引擎
func Rpc(sbom string) bool {
	var recvSize = 1024 * 1024 * 1024 * 1024 * 1024
	host := "127.0.0.1"
	conn, err := grpc.Dial(host+":8080", grpc.WithInsecure(), grpc.WithDefaultCallOptions(grpc.MaxCallRecvMsgSize(recvSize)))
	if err != nil {
		fmt.Println(err.Error())
		return false
	}
	// 创建Themis服务的客户端
	t := ryzesca.NewRyzescaClient(conn)

	end, err := t.RunRyzescaCycloneDX(context.Background(), &ryzesca.RyzescaParams{
		IdentifierPackage: true,
		FindingPackageVul: true,
		SimplePackageVul:  false,
		FindingSummary:    false,
		OnlyFindings:      false,
		OnlyJsonSummary:   false,
		CyclonedxJsonpath: "",
		CyclonedxJson:     sbom})
	if err != nil {
		fmt.Println("********************", err.Error())
		return false
	}
	//create, _ := os.Create("res.json")
	//marshal, _ := json.Marshal(end.Files)
	//_, _ = create.Write(marshal)
	//_ = create.Close()
	fmt.Println(end.Files)
	return true
}
