development:
  # 是否是开发模式
  develop: true
server:
  port: 8080
log:
  # 日志文件最大大小（m）
  MaxSize: 10
  # 日志文件最大保留个数
  MaxBackups: 100
  # 日志文件最大保存时间（天）
  MaxAge: 60
mysql:
  # host: 127.123.2.1
  host: 127.0.0.1
  port: 3306
  user: root
  password: 123456
  database: themis
  # 设置最大空闲连接
  MaxIdleCons: 10
  # 设置最大打开连接
  MaxOpenCons: 100

